##### 远程仓库和本地仓库冲突

假设有多个开发者同时 clone 了远程 仓库的 代码

多个开发者同时使用或者操作 git 中的同一个文件，最后在依次提交和 push 的时候，第一个操作的是可以正常提交的，而之后的开发者想要执行 push 操作的时候，就会报冲突异常 conflict 。 

conflict 会指定那个文件有冲突

CONFLICT (content): Merge conflict in test

```python
$ git push github master
To https://github.com/StefanLei/blog-flask.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/StefanLei/blog-flask.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

```

然后我们就需要 git pull ，作用是 把远程最新的代码 下载下来同时和合并本地的代码，

执行 git pull 后，本地test文件的代码就变成了

```
<<<<<<< HEAD
test aaaaaaa
=======
test
new
>>>>>>> 61e6ca4f7a9921b6afce9c57a26b9609a5210ec5

```

然后我们对代码文件进行修改就行了， 需要根据实际情况手动的修改代码，然后保存

最后把 本地的仓库 push 到远程去就行